ephemit_evenement_creer:
    pattern:  /evenement/creer
    defaults: { _controller: EphemitEvenementBundle:Evenement:creer }
ephemit_evenement_list:
    pattern:  /mes-evenements
    defaults: { _controller: EphemitEvenementBundle:Evenement:liste }
ephemit_evenement_supprimer:
    pattern:  /mes-evenements/supprimer/{id}
    defaults: { _controller: EphemitEvenementBundle:Evenement:supprimer }
    options:
        expose: true
ephemit_evenement_modifier:
    pattern:  /mes-evenements/modifier/{id}
    defaults: { _controller: EphemitEvenementBundle:Evenement:modifier }
    options:
        expose: true
