ephemit_evenement_creer:
    pattern:  /page/creer
    defaults: { _controller: EphemitEvenementBundle:Evenement:creer }
    options:
        expose: true
ephemit_evenement_list:
    pattern:  /mes-pages
    defaults: { _controller: EphemitEvenementBundle:Evenement:liste }
ephemit_evenement_supprimer:
    pattern:  /mes-pages/supprimer/{id}
    defaults: { _controller: EphemitEvenementBundle:Evenement:supprimer }
    options:
        expose: true
ephemit_evenement_modifier:
    pattern:  /page/admin/modifier/{cle}
    defaults: { _controller: EphemitEvenementBundle:Evenement:modifier }
    options:
        expose: true
ephemit_favoris_ajouter:
    pattern:  /favoris/ajouter/{id}
    defaults: { _controller: EphemitEvenementBundle:Evenement:ajouterFavoris }
    options:
        expose: true
ephemit_fiche_evenement:
    pattern:  /page/{cle}
    defaults: { _controller: EphemitEvenementBundle:Evenement:page }
    options:
        expose: true
ephemit_gerer_evenement:
    pattern:  /page/gerer/{cle}
    defaults: { _controller: EphemitEvenementBundle:Evenement:gerer }
ephemit_page_admin:
    pattern:  /page/admin/{cle}
    defaults: { _controller: EphemitEvenementBundle:Evenement:adminPage }
    options:
        expose: true
ephemit_page_apercu:
    pattern:  /page/apercu/{cle}
    defaults: { _controller: EphemitEvenementBundle:Evenement:apercu }
    options:
        expose: true