parameters:
#    ephemit_evenement.example.class: Ephemit\EvenementBundle\Example

services:
#    ephemit_evenement.example:
#        class: %ephemit_evenement.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
