parameters:
    ephemit_site.example.class: Ephemit\SiteBundle\Example

services:
    ephemit_evenement.file.namer:
        class: %ephemit_site.namer.class%
        arguments: [@service_id, "plain_value", %parameter%]
