parameters:
#    ephemit_site.example.class: Ephemit\SiteBundle\Example

services:
#    ephemit_site.example:
#        class: %ephemit_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
